apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "aoaisim.fullname" . }}-pv
  labels:
    {{- include "aoaisim.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  mountOptions:
    - uid=1000
    - gid=1000
    - nobrl
    - mfsymlinks
    - cache=none
  csi:
    {{- with .Values.azureFiles }}
    driver: file.csi.azure.com
    volumeHandle: "{{ .azureStorageAccountName }}#{{ .fileShareName }}"
    volumeAttributes:
      shareName: {{ .fileShareName | quote }}
    {{- end }}
    nodeStageSecretRef:
      name: {{ include "aoaisim.fullname" . }}-storage
      namespace: {{ .Release.Namespace }}
