apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aoaisim.fullname" . }}-pvc
  labels:
    {{- include "aoaisim.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi