apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aoaisim.fullname" . }}-storage
  labels:
    {{- include "aoaisim.labels" . | nindent 4 }}
{{- with .Values.azureFiles }}
data:
  azurestorageaccountname: {{ .azureStorageAccountName | b64enc | quote }}
  azurestorageaccountkey: {{ .azureStorageAccountKey | b64enc | quote }}
{{- end }}