
@aoai_endpoint={{$dotenv %endpoint_env_var}}
@aoai_key={{$dotenv %key_env_var}}
@aoai_deployment={{$dotenv %deployment_env_var}}


################################################################
#
# Completions
# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions

POST {{aoai_endpoint}}/openai/deployments/{{aoai_deployment}}/completions?api-version=2023-05-15
Content-Type: application/json
api-key: {{aoai_key}}

{
  "model": "gpt-5-turbo-1",
  "prompt": "Once upon a time",
  "max_tokens": 10
}

###

POST {{aoai_endpoint}}/openai/deployments/{{aoai_deployment}}/completions?api-version=2023-05-15
Content-Type: application/json
api-key: {{aoai_key}}

{
  "model": "gpt-5-turbo-1",
  "prompt": "Once upon a time"
}

###
