@aoai_endpoint={{$dotenv %endpoint_env_var}}
@aoai_key={{$dotenv %key_env_var}}
@aoai_deployment={{$dotenv %whisper_deploy_env_var}}

################################################################
#
# Translations
# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#translations

POST {{aoai_endpoint}}/openai/deployments/{{aoai_deployment}}/audio/translations?api-version=2024-06-01
Content-Type: multipart/form-data; boundary=---7MA4YWxkTrZu0gW
api-key: {{aoai_key}}

-----7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="response_format"

json
-----7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="short-spanish.mp3"
Content-Type: audio/mpeg

< ./short-spanish.mp3
-----7MA4YWxkTrZu0gW--

###
curl https://wthack2.openai.azure.com/openai/deployments/whisper-hack/audio/translations?api-version=2024-06-01  \
-H "api-key: 5d51515468a4432a95f1a121eb9a6d43"  \
-H "Content-Type: multipart/form-data"  \
-F file="@/workspaces/aoai-api-simulator/http/short-spanish.mp3" \
-F response_type="json"