apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aoaisim.fullname" . }}-openai-deployment-config
  labels:
    {{- include "aoaisim.labels" . | nindent 4 }}
data:
  simulator_deployment_config.json: |-
    {{- .Files.Get ".openai_deployment_config.json" | nindent 4 }}